plugins: ./_plugins
auto: true
safe: true
server: true
markdown: kramdown
pygments: true
permalink: /:title.html
#exclude: [shower,themes]

default_theme: ribbon
default_lang: en
default_body_class: list

author:
    name: Andrey Kulakov
    url:  http://8xx8.ru
    company:
        name: Undev
        url:  http://undev.ru/

fork_url: https://github.com/shower/shower
progress: true
